### PR TITLE
PEBE token in swap.harmony

### PR DESCRIPTION
**Pull request by Mintbes**
Hi, here you can find my submission for including PEBE in swap.harmony.one.
Do not hesitate to contact me for any request.
Thanks for the support,
Mintbes

### CODE REVIEW

**Comment by msvstj** [comment]
Hello @Mintbes,
The address you provided is for WONE, not for PEBE.

` "address": "0xcf664087a5bb0237a0bad6742852ec6c8d69a27a",`

https://github.com/harmony-one/swap-token-list/pull/17/files#diff-a76fd610d878193d6544e190e786f5527863d5d04acca378b9d1178d3e7c15e2R169

We will review again once tokenlist is updated with the correct address

**Comment by Mintbes** [comment]
Hola Marta, ups!, you are right.
Done, thanks.

**Comment by msvstj** [comment]
No issues tech side, contract is [verified](https://explorer.harmony.one/address/0x5f6f4c224a39cec9aa142648dbde7b611591a0e7?tab=read_proxy&shard=0). 

Pending approval from Harmony side @sophoah

**Comment by ONETheo** [comment]
No issues business side.

**Comment by msvstj** [comment]
@Mintbes 
Approved from both sides. 
Since the branch is a bit outdated, could you resolve conflicts and then we will merge :)

**Review by sophoah — APPROVED** [review]

**Comment by Mintbes** [comment]
Hello @sophoah 
Conflicts resolved. Thanks for your support.
Mintbes

**Pull request merged**
