### PR TITLE
Update tokenlist.json

### PR DESCRIPTION
**Pull request by PeaceLoveHarmony**
The contract for PEACE is verified and audited, Thank you!

### CODE REVIEW

**Review by sophoah — APPROVED** [review]

**Comment by PeaceLoveHarmony** [comment]
Will do, thank you @msvstj 💙

**Comment by PeaceLoveHarmony** [comment]
I believe I fixed it @msvstj

**Comment by msvstj** [comment]
I don't see icon file in your branch in PEACE folder: https://github.com/PeaceLoveHarmony/swap-token-list/tree/patch-1/assets

**Comment by mzfshark** [comment]
switch this PR for new one: https://github.com/harmony-one/swap-token-list/pull/13

**Pull request merged**
