### PR TITLE
Add Neurons token

### PR DESCRIPTION
**Pull request by mzfshark**
$Neurons: Early Access Investment on Harmony Blockchain
$Neurons, a pre-release token, was designed as an early access investment exclusively available on the Harmony Blockchain. This strategic token will serve as a precursor to the official project token, providing early supporters with unique opportunities.

Privileged Access for $Neurons V1 Holders
Holders of $Neurons V1(https://info.swap.country/#/harmony/tokens/0xfb5e55b89dbeaf01797be3f744bd556e4d9fb259) V1 tokens are in for a special treat. As the project transitions to the official token launch, these early supporters will receive a privileged spot. The $Neurons V1 tokens serve as access rights, ensuring holders exclusive benefits and opportunities during the official launch of the project token.

Gateway to the Official Project Token Launch
Consider your $Neurons V1 tokens as golden tickets, providing you with a front-row seat at the official project token launch. This exclusive access highlights our appreciation for the early support and commitment shown by $Neurons V1 holders.

### CODE REVIEW

**Comment by msvstj** [comment]
No issues from technical side.

**Comment by ONETheo** [comment]
More info needed on business side.

Needed: Link to main site, or documentation.

**Comment by mzfshark** [comment]
> More info needed on business side.
> 
> Needed: Link to main site, or documentation.

Website: https://thinkincoin.com
Documentation: https://whitepaper.thinkincoin.com/
Twitter (x): https://twitter.com/ThinkinCoin
Medium: https://thinkincoin.medium.com/ 
Telegram: https://t.me/ThinkinCoin
Youtube: https://www.youtube.com/watch?v=R1spsfUqtA8&ab_channel=ThinkinCoin

**Comment by ONETheo** [comment]
No issues from business side.

**Comment by msvstj** [comment]
@mzfshark, Can you please fix merge conflicts so we will proceed with addition.

Thank you

**Comment by msvstj** [comment]
Thank you @mzfshark , could you please recheck whether there are any more merge conflicts or try to merge main to your branch?
image

**Comment by mzfshark** [comment]
> Thank you @mzfshark , could you please recheck whether there are any more merge conflicts or try to merge main to your branch? image

conflicts solved.

**Comment by msvstj** [comment]
> > Thank you @mzfshark , could you please recheck whether there are any more merge conflicts or try to merge main to your branch? image
> 
> conflicts solved.

Thank you, but it seems you accepted only your incoming change (with this PR you would overwrite the HOUND token)
image

(You can check in your version the overwritten token does not exist. Please add a new token instead). Thank you

**Comment by mzfshark** [comment]
> (You can check in your version the overwritten token does not exist. Please add a new token instead). Thank you

Sorry for that! Not enough coffee today ;)

**Pull request merged**
