### PR TITLE
Add baseUSDC Token

### PR DESCRIPTION
**Pull request by metaoneklas**
Pull request to add baseUSDC Token to the main swap list.

### CODE REVIEW

**Comment by sophoah** [comment]
approved

**Comment by msvstj** [comment]
Hello @metaoneklas 
Please increment the version of the file:
[example](https://github.com/harmony-one/swap-token-list/blob/main/README.md?plain=1#L34)
and add timestamp of the latest edit: 
[example](https://github.com/harmony-one/swap-token-list/blob/main/README.md?plain=1#L42)

Other than that - no issues. Token appears in layer zero bridge.

**Comment by msvstj** [comment]
One more change required:
match decimals to the contract value. In the example it is 18, whereas baseUSDC has 6;

Note* token is not verified, however, it does appear in assets list: https://bridge.harmony.one/tokens.

**Comment by msvstj** [comment]
Thank you, token-list is formatted correctly, version incremented, token data matches.

**Pull request merged**
