### PR TITLE
Add bscUSDT

### PR DESCRIPTION
**Pull request by metaoneklas**
Adding, as requested by the protoFire team the bscUSDT address to the officially supported tokens.

### CODE REVIEW

**Comment by msvstj** [comment]
Hello @metaoneklas ,
1. Could you please solve merge conflicts?
2. Also token name should match the contract data: [token in explorer](https://explorer.harmony.one/token/0x9A89d0e1b051640C6704Dde4dF881f73ADFEf39a?shard=0) 
`name: Tether USD`

No issues otherwise, will be reviewed once again after changes are applied.

Pending approval from harmony side. @sophoah

**Comment by metaoneklas** [comment]
Changed according to feedback.

**Comment by msvstj** [comment]
No issues tech side. 
@sophoah

**Comment by ONETheo** [comment]
No issues business side.

**Pull request merged**
